settings:
  title: 'Genuine-Tv Status Page'
  url: 'https://genuinetv-status.cybersquads.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Application Server # unique identifier
    name: Application Server
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://sadakalotv.online/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Movies Server 1[fs.plus.net.bd]
    name: Movies Server 1
    description: 'Built for anything connected to the Internet.'
    url: 'https://fs.plus.net.bd/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Movies Server 2[103.121.62.18]
    name: Movies Server 2
    url: 'http://103.121.62.18/collection/'
    method: GET
    expectStatus: 200
